# Generated by Django 5.2 on 2025-04-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresult',
            name='computer_choice',
            field=models.CharField(choices=[('rock', 'Rock'), ('paper', 'Paper'), ('scissors', 'Scissors')], max_length=10),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='player_choice',
            field=models.CharField(choices=[('rock', 'Rock'), ('paper', 'Paper'), ('scissors', 'Scissors')], max_length=10),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='result',
            field=models.CharField(choices=[('win', 'Win'), ('lose', 'Lose'), ('draw', 'Draw')], max_length=10),
        ),
    ]
